"""
gentypes.py — generate per-framework typings for the Dojo NG components from
custom-elements.json (the CEM). Run from components/ AFTER gencem.py:

    python3 gentypes.py

Output (types/):
    dojo.d.ts   — augments @dojo-ng/framework's tsx.JSX.IntrinsicElements
    react.d.ts   — augments React's JSX.IntrinsicElements
    solid.d.ts   — augments solid-js JSX.IntrinsicElements + custom events
    vue.d.ts     — augments Vue's GlobalComponents
    README.md    — how to wire each into a consumer's tsconfig

The manifest is the single source of truth; these are generated from it. Prop
value types are taken by INDEXED ACCESS on the imported element class
(e.g. `DjButton["kind"]`), so they stay exactly accurate without re-importing or
re-deriving the components' alias types. No runtime wrappers are produced — the
components pass Custom Elements Everywhere, so consumers need types, not shims.
"""

import json
import os

CEM = "custom-elements.json"
OUT = "types"


def load_elements():
    cem = json.load(open(CEM))
    els = []
    for m in cem["modules"]:
        pkg = m["path"].split("/")[1]
        for dec in m.get("declarations", []):
            if not dec.get("customElement"):
                continue
            fields = [x for x in dec.get("members", []) if x.get("kind") == "field"]
            props = [{"prop": f["name"], "attr": f.get("attribute")} for f in fields]
            events = [e["name"] for e in dec.get("events", [])]
            els.append(
                {
                    "pkg": pkg,
                    "tag": dec["tagName"],
                    "cls": dec["name"],
                    "props": props,
                    "events": events,
                }
            )
    return sorted(els, key=lambda e: e["tag"])


def imports(els):
    return "\n".join(
        f'import type {{ {e["cls"]} }} from "@dojo-ng/{e["pkg"]}";' for e in els
    )


# ---------------------------------------------------------------------------
# React  (JSX.IntrinsicElements on the "react" module — React 19+)
# ---------------------------------------------------------------------------


def gen_react(els):
    blocks = []
    for e in els:
        rows = []
        for p in e["props"]:
            key = p["attr"] or p["prop"]  # JSX uses the attribute name
            rows.append(f'        "{key}"?: {e["cls"]}["{p["prop"]}"];')
        body = "\n".join(rows)
        blocks.append(
            f'      "{e["tag"]}": DjProps<{e["cls"]}>'
            + (f" & {{\n{body}\n      }};" if rows else ";")
        )
    return f"""// Generated by gentypes.py from custom-elements.json. Do not edit by hand.
//
// React 19+ typings for the Dojo NG custom elements. Attributes are keyed by
// their HTML attribute name; React 19 also accepts the camelCase property form.
// Custom events have no standard JSX form — bind them with a ref +
// addEventListener, or use the framework adapter of your choice.
import type {{ DetailedHTMLProps, HTMLAttributes }} from "react";
{imports(els)}

type DjProps<T> = DetailedHTMLProps<HTMLAttributes<T>, T>;

declare module "react" {{
  namespace JSX {{
    interface IntrinsicElements {{
{chr(10).join(blocks)}
    }}
  }}
}}
"""


# ---------------------------------------------------------------------------
# Solid  (solid-js JSX.IntrinsicElements + on:<event> custom events)
# ---------------------------------------------------------------------------


def gen_solid(els):
    blocks, ev_rows = [], []
    for e in els:
        rows = [
            f'        "{(p["attr"] or p["prop"])}"?: {e["cls"]}["{p["prop"]}"];'
            for p in e["props"]
        ]
        body = "\n".join(rows)
        blocks.append(
            f'      "{e["tag"]}": JSX.HTMLAttributes<{e["cls"]}>'
            + (f" & {{\n{body}\n      }};" if rows else ";")
        )
        for ev in e["events"]:
            ev_rows.append(f'      "{ev}": CustomEvent;')
    # Deduplicate event names (Solid's on:/oncapture: maps are global).
    seen, ev_uniq = set(), []
    for r in ev_rows:
        if r not in seen:
            seen.add(r)
            ev_uniq.append(r)
    events_block = "\n".join(ev_uniq)
    return f"""// Generated by gentypes.py from custom-elements.json. Do not edit by hand.
//
// Solid typings for the Dojo NG custom elements. Props are keyed by attribute
// name; custom events bind with Solid's `on:<name>` syntax, typed below.
import type {{ JSX }} from "solid-js";
{imports(els)}

declare module "solid-js" {{
  namespace JSX {{
    interface IntrinsicElements {{
{chr(10).join(blocks)}
    }}
    interface CustomEvents {{
{events_block}
    }}
    interface CustomCaptureEvents {{
{events_block}
    }}
  }}
}}
"""


# ---------------------------------------------------------------------------
# Vue  (GlobalComponents on the "vue" module — Volar template type-check)
# ---------------------------------------------------------------------------


def gen_vue(els):
    rows = []
    for e in els:
        props = "; ".join(
            f'{p["prop"]}?: {e["cls"]}["{p["prop"]}"]' for p in e["props"]
        )
        emits = ", ".join(f'"{ev}": (e: CustomEvent) => void' for ev in e["events"])
        emits_t = f"{{ {emits} }}" if emits else "{}"
        rows.append(
            f'    "{e["tag"]}": DefineComponent<{{ {props} }}, {{}}, {{}}, {{}}, {{}}, {{}}, {emits_t}>;'
        )
    return f"""// Generated by gentypes.py from custom-elements.json. Do not edit by hand.
//
// Vue 3 typings for the Dojo NG custom elements (Volar template type-checking).
// Props map to the components' properties; events are typed as emits, so
// templates can bind `@dj-close` and friends with a typed payload.
// GlobalComponents is augmented on @vue/runtime-core (the canonical Volar target).
import type {{ DefineComponent }} from "vue";
{imports(els)}

declare module "@vue/runtime-core" {{
  interface GlobalComponents {{
{chr(10).join(rows)}
  }}
}}
"""


# ---------------------------------------------------------------------------
# Dojo NG renderer  (tsx.JSX.IntrinsicElements on @dojo-ng/framework)
# ---------------------------------------------------------------------------


def gen_dojo(els):
    blocks = []
    for e in els:
        rows = [
            f'        "{(p["attr"] or p["prop"])}"?: {e["cls"]}["{p["prop"]}"];'
            for p in e["props"]
        ]
        body = "\n".join(rows)
        blocks.append(
            f'      "{e["tag"]}": DjVNodeBase'
            + (f" & {{\n{body}\n      }};" if rows else ";")
        )
    return f"""// Generated by gentypes.py from custom-elements.json. Do not edit by hand.
//
// Dojo NG renderer (tsx) typings for the custom elements. Registers each dj- tag
// on the renderer's JSX.IntrinsicElements so `.tsx` written against
// @dojo-ng/framework's `tsx` factory type-checks (`<dj-button kind="outlined">`).
// Prop value types come from the component classes (e.g. DjButton["kind"]).
//
// REQUIRES the renderer to ship its base JSX types (the `tsx.JSX` namespace with
// the standard intrinsic elements), just as the React/Vue/Solid targets require
// those frameworks' own types. Until the fork publishes a vdom.d.ts, the
// types/verify harness supplies a minimal stand-in.
{imports(els)}

declare module "@dojo-ng/framework" {{
  namespace tsx.JSX {{
    interface IntrinsicElements {{
{chr(10).join(blocks)}
    }}
  }}
}}

// Dojo VNode properties common to every element (mirrors VNodeProperties:
// key/classes/styles plus on* event handlers). Named dj- props above add precise
// types on top; an unknown `kind` value still errors because the explicit member
// is narrower than this base.
interface DjVNodeBase {{
  key?: string | number;
  classes?: string | null | undefined | (string | null | undefined | boolean)[];
  styles?: Partial<CSSStyleDeclaration>;
  [handler: `on${{string}}`]: ((event: any) => void) | undefined;
}}
"""


README = """# Dojo NG framework typings

Generated from `custom-elements.json` by `gentypes.py` (run `npm run types`).
These add type-checking for the `dj-*` custom elements in React, Solid, and Vue.
They are **types only** — Dojo NG components are standard custom elements that
pass Custom Elements Everywhere, so no runtime wrappers are needed.

Prop value types are taken straight from the component classes (e.g.
`DjButton["kind"]`), so they always match the components.

## React (19+)

Reference the declaration once (e.g. in your app's `env.d.ts` or any file in the
compilation):

```ts
/// <reference types="@dojo-ng/components/types/react" />
```

Attributes are keyed by their HTML name (`icon-position`); React 19 also accepts
the camelCase property form. Custom events have no standard JSX form — bind them
with a `ref` + `addEventListener`.

## Solid

```ts
/// <reference types="@dojo-ng/components/types/solid" />
```

Props are keyed by attribute name; custom events use Solid's `on:` syntax, e.g.
`<dj-dialog on:dj-close={...}>`, typed for you.

## Vue 3

```ts
/// <reference types="@dojo-ng/components/types/vue" />
```

Props and events are typed on `GlobalComponents`, so templates type-check:
`<dj-select :options="opts" @change="..." />`. Bind events with `@dj-close`.

## Dojo NG renderer (tsx)

```ts
/// <reference types="@dojo-ng/components/types/dojo" />
```

Registers the `dj-` tags on the renderer's `tsx.JSX.IntrinsicElements`, so `.tsx`
written against `@dojo-ng/framework`'s `tsx` factory type-checks
(`<dj-button kind="outlined">`). Requires the renderer to ship its base JSX types
(the `tsx.JSX` namespace) — the same way the other targets require their
framework's types.

Regenerate after any component change: `npm run cem && npm run types`.
"""


def main():
    els = load_elements()
    os.makedirs(OUT, exist_ok=True)
    open(f"{OUT}/react.d.ts", "w").write(gen_react(els))
    open(f"{OUT}/solid.d.ts", "w").write(gen_solid(els))
    open(f"{OUT}/vue.d.ts", "w").write(gen_vue(els))
    open(f"{OUT}/dojo.d.ts", "w").write(gen_dojo(els))
    open(f"{OUT}/README.md", "w").write(README)
    print(
        f"types: {len(els)} elements → {OUT}/react.d.ts, solid.d.ts, vue.d.ts, dojo.d.ts"
    )


if __name__ == "__main__":
    main()
