// Generated by gentypes.py from custom-elements.json. Do not edit by hand.
//
// Dojo NG renderer (tsx) typings for the custom elements. Registers each dj- tag
// on the renderer's JSX.IntrinsicElements so `.tsx` written against
// @dojo-ng/framework's `tsx` factory type-checks (`<dj-button kind="outlined">`).
// Prop value types come from the component classes (e.g. DjButton["kind"]).
//
// REQUIRES the renderer to ship its base JSX types (the `tsx.JSX` namespace with
// the standard intrinsic elements), just as the React/Vue/Solid targets require
// those frameworks' own types. Until the fork publishes a vdom.d.ts, the
// types/verify harness supplies a minimal stand-in.
import type { DjAccordion } from "@dojo-ng/accordion";
import type { DjActionButton } from "@dojo-ng/action-button";
import type { DjAudio } from "@dojo-ng/audio";
import type { DjAvatar } from "@dojo-ng/avatar";
import type { DjBoard } from "@dojo-ng/board";
import type { DjBreadcrumbGroup } from "@dojo-ng/breadcrumb-group";
import type { DjButton } from "@dojo-ng/button";
import type { DjCalendar } from "@dojo-ng/calendar";
import type { DjCard } from "@dojo-ng/card";
import type { DjCarousel } from "@dojo-ng/carousel";
import type { DjChart } from "@dojo-ng/chart";
import type { DjCheckbox } from "@dojo-ng/checkbox";
import type { DjCheckboxGroup } from "@dojo-ng/checkbox-group";
import type { DjChip } from "@dojo-ng/chip";
import type { DjChipTypeahead } from "@dojo-ng/chip-typeahead";
import type { DjColorPicker } from "@dojo-ng/color-picker";
import type { DjConstrainedInput } from "@dojo-ng/constrained-input";
import type { DjContextMenu } from "@dojo-ng/context-menu";
import type { DjContextPopup } from "@dojo-ng/context-popup";
import type { DjDataGrid } from "@dojo-ng/data-grid";
import type { DjDateInput } from "@dojo-ng/date-input";
import type { DjDialog } from "@dojo-ng/dialog";
import type { DjEmailInput } from "@dojo-ng/email-input";
import type { DjFileInput } from "@dojo-ng/file-input";
import type { DjFloatingActionButton } from "@dojo-ng/floating-action-button";
import type { DjForm } from "@dojo-ng/form";
import type { DjGlobalEvent } from "@dojo-ng/global-event";
import type { DjGrid } from "@dojo-ng/grid";
import type { DjHeader } from "@dojo-ng/header";
import type { DjHeaderCard } from "@dojo-ng/header-card";
import type { DjHelperText } from "@dojo-ng/helper-text";
import type { DjIcon } from "@dojo-ng/icon";
import type { DjLabel } from "@dojo-ng/label";
import type { DjList } from "@dojo-ng/list";
import type { DjLoadingIndicator } from "@dojo-ng/loading-indicator";
import type { DjNativeSelect } from "@dojo-ng/native-select";
import type { DjNumberInput } from "@dojo-ng/number-input";
import type { DjPagination } from "@dojo-ng/pagination";
import type { DjPasswordInput } from "@dojo-ng/password-input";
import type { DjPopup } from "@dojo-ng/popup";
import type { DjPopupConfirmation } from "@dojo-ng/popup-confirmation";
import type { DjProgress } from "@dojo-ng/progress";
import type { DjRadio } from "@dojo-ng/radio";
import type { DjRadioGroup } from "@dojo-ng/radio-group";
import type { DjRangeSlider } from "@dojo-ng/range-slider";
import type { DjRate } from "@dojo-ng/rate";
import type { DjResult } from "@dojo-ng/result";
import type { DjRichText } from "@dojo-ng/rich-text";
import type { DjSelect } from "@dojo-ng/select";
import type { DjSlidePane } from "@dojo-ng/slide-pane";
import type { DjSlider } from "@dojo-ng/slider";
import type { DjSnackbar } from "@dojo-ng/snackbar";
import type { DjSpeedDial } from "@dojo-ng/speed-dial";
import type { DjSplitPanel } from "@dojo-ng/split-panel";
import type { DjStack } from "@dojo-ng/stack";
import type { DjSwitch } from "@dojo-ng/switch";
import type { DjTabContainer } from "@dojo-ng/tab-container";
import type { DjText } from "@dojo-ng/text";
import type { DjTextArea } from "@dojo-ng/text-area";
import type { DjTextInput } from "@dojo-ng/text-input";
import type { DjTheme } from "@dojo-ng/theme";
import type { DjThreeColumnLayout } from "@dojo-ng/three-column-layout";
import type { DjTimePicker } from "@dojo-ng/time-picker";
import type { DjTitlePane } from "@dojo-ng/title-pane";
import type { DjToolbar } from "@dojo-ng/toolbar";
import type { DjTooltip } from "@dojo-ng/tooltip";
import type { DjTransition } from "@dojo-ng/transition";
import type { DjTransitionGroup } from "@dojo-ng/transition-group";
import type { DjTree } from "@dojo-ng/tree";
import type { DjTriggerPopup } from "@dojo-ng/trigger-popup";
import type { DjTwoColumnLayout } from "@dojo-ng/two-column-layout";
import type { DjTypeahead } from "@dojo-ng/typeahead";
import type { DjVideo } from "@dojo-ng/video";
import type { DjWizard } from "@dojo-ng/wizard";

declare module "@dojo-ng/framework" {
  namespace tsx.JSX {
    interface IntrinsicElements {
      "dj-accordion": DjVNodeBase & {
        "exclusive"?: DjAccordion["exclusive"];
      };
      "dj-action-button": DjVNodeBase;
      "dj-audio": DjVNodeBase & {
        "src"?: DjAudio["src"];
        "label"?: DjAudio["label"];
        "preload"?: DjAudio["preload"];
      };
      "dj-avatar": DjVNodeBase & {
        "type"?: DjAvatar["type"];
        "size"?: DjAvatar["size"];
        "src"?: DjAvatar["src"];
        "alt"?: DjAvatar["alt"];
        "secondary"?: DjAvatar["secondary"];
        "outline"?: DjAvatar["outline"];
      };
      "dj-board": DjVNodeBase & {
        "data"?: DjBoard["data"];
        "lanes"?: DjBoard["lanes"];
        "group-by"?: DjBoard["groupBy"];
        "card-key"?: DjBoard["cardKey"];
        "card-title"?: DjBoard["cardTitle"];
        "label"?: DjBoard["label"];
        "renderCard"?: DjBoard["renderCard"];
        "draggable"?: DjBoard["draggable"];
      };
      "dj-breadcrumb-group": DjVNodeBase & {
        "items"?: DjBreadcrumbGroup["items"];
      };
      "dj-button": DjVNodeBase & {
        "disabled"?: DjButton["disabled"];
        "kind"?: DjButton["kind"];
        "type"?: DjButton["type"];
        "name"?: DjButton["name"];
        "value"?: DjButton["value"];
        "label"?: DjButton["label"];
        "icon-position"?: DjButton["iconPosition"];
        "title"?: DjButton["title"];
      };
      "dj-calendar": DjVNodeBase & {
        "value"?: DjCalendar["value"];
        "name"?: DjCalendar["name"];
        "min"?: DjCalendar["min"];
        "max"?: DjCalendar["max"];
        "locale"?: DjCalendar["locale"];
        "first-day-of-week"?: DjCalendar["firstDayOfWeek"];
      };
      "dj-card": DjVNodeBase & {
        "kind"?: DjCard["kind"];
        "square"?: DjCard["square"];
        "title"?: DjCard["title"];
        "subtitle"?: DjCard["subtitle"];
        "media-src"?: DjCard["mediaSrc"];
        "media-title"?: DjCard["mediaTitle"];
        "clickable"?: DjCard["clickable"];
      };
      "dj-carousel": DjVNodeBase & {
        "per-view"?: DjCarousel["perView"];
        "nav"?: DjCarousel["nav"];
        "dots"?: DjCarousel["dots"];
        "label"?: DjCarousel["label"];
      };
      "dj-chart": DjVNodeBase & {
        "data"?: DjChart["data"];
        "series"?: DjChart["series"];
        "category-key"?: DjChart["categoryKey"];
        "type"?: DjChart["type"];
        "orientation"?: DjChart["orientation"];
        "stacked"?: DjChart["stacked"];
        "show-legend"?: DjChart["showLegend"];
        "show-grid"?: DjChart["showGrid"];
        "x-label"?: DjChart["xLabel"];
        "y-label"?: DjChart["yLabel"];
        "y-label-right"?: DjChart["yLabelRight"];
        "label"?: DjChart["label"];
        "markers"?: DjChart["markers"];
        "x-key"?: DjChart["xKey"];
        "size-key"?: DjChart["sizeKey"];
        "inner-radius"?: DjChart["innerRadius"];
        "center-label"?: DjChart["centerLabel"];
        "center-sub-label"?: DjChart["centerSubLabel"];
        "legend-toggle"?: DjChart["legendToggle"];
        "brush"?: DjChart["brush"];
        "numberFormat"?: DjChart["numberFormat"];
        "formatY"?: DjChart["formatY"];
        "formatX"?: DjChart["formatX"];
      };
      "dj-checkbox": DjVNodeBase & {
        "checked"?: DjCheckbox["checked"];
        "value"?: DjCheckbox["value"];
        "name"?: DjCheckbox["name"];
        "disabled"?: DjCheckbox["disabled"];
        "readonly"?: DjCheckbox["readonly"];
        "required"?: DjCheckbox["required"];
        "label-hidden"?: DjCheckbox["labelHidden"];
      };
      "dj-checkbox-group": DjVNodeBase & {
        "options"?: DjCheckboxGroup["options"];
        "value"?: DjCheckboxGroup["value"];
        "name"?: DjCheckboxGroup["name"];
        "label"?: DjCheckboxGroup["label"];
        "orientation"?: DjCheckboxGroup["orientation"];
        "disabled"?: DjCheckboxGroup["disabled"];
      };
      "dj-chip": DjVNodeBase & {
        "disabled"?: DjChip["disabled"];
        "checked"?: DjChip["checked"];
        "clickable"?: DjChip["clickable"];
        "closeable"?: DjChip["closeable"];
      };
      "dj-chip-typeahead": DjVNodeBase & {
        "options"?: DjChipTypeahead["options"];
        "value"?: DjChipTypeahead["value"];
        "name"?: DjChipTypeahead["name"];
        "label"?: DjChipTypeahead["label"];
        "placeholder"?: DjChipTypeahead["placeholder"];
        "disabled"?: DjChipTypeahead["disabled"];
        "duplicates"?: DjChipTypeahead["duplicates"];
        "allow-new"?: DjChipTypeahead["allowNew"];
        "position"?: DjChipTypeahead["position"];
      };
      "dj-color-picker": DjVNodeBase & {
        "format"?: DjColorPicker["format"];
        "alpha"?: DjColorPicker["alpha"];
        "swatches"?: DjColorPicker["swatches"];
        "label"?: DjColorPicker["label"];
        "name"?: DjColorPicker["name"];
        "disabled"?: DjColorPicker["disabled"];
        "get"?: DjColorPicker["get"];
      };
      "dj-constrained-input": DjVNodeBase & {
        "validator"?: DjConstrainedInput["validator"];
      };
      "dj-context-menu": DjVNodeBase & {
        "options"?: DjContextMenu["options"];
      };
      "dj-context-popup": DjVNodeBase & {
        "open"?: DjContextPopup["open"];
      };
      "dj-data-grid": DjVNodeBase & {
        "columns"?: DjDataGrid["columns"];
        "data"?: DjDataGrid["data"];
        "selection-mode"?: DjDataGrid["selectionMode"];
        "row-height"?: DjDataGrid["rowHeight"];
        "height"?: DjDataGrid["height"];
        "plugins"?: DjDataGrid["plugins"];
      };
      "dj-date-input": DjVNodeBase & {
        "value"?: DjDateInput["value"];
        "name"?: DjDateInput["name"];
        "label"?: DjDateInput["label"];
        "min"?: DjDateInput["min"];
        "max"?: DjDateInput["max"];
        "disabled"?: DjDateInput["disabled"];
        "required"?: DjDateInput["required"];
      };
      "dj-dialog": DjVNodeBase & {
        "open"?: DjDialog["open"];
        "closeable"?: DjDialog["closeable"];
        "modal"?: DjDialog["modal"];
        "underlay"?: DjDialog["underlay"];
        "role"?: DjDialog["role"];
        "close-text"?: DjDialog["closeText"];
      };
      "dj-email-input": DjVNodeBase & {
        "type"?: DjEmailInput["type"];
      };
      "dj-file-input": DjVNodeBase & {
        "accept"?: DjFileInput["accept"];
        "multiple"?: DjFileInput["multiple"];
        "required"?: DjFileInput["required"];
        "max-size"?: DjFileInput["maxSize"];
        "label"?: DjFileInput["label"];
        "name"?: DjFileInput["name"];
        "disabled"?: DjFileInput["disabled"];
      };
      "dj-floating-action-button": DjVNodeBase & {
        "size"?: DjFloatingActionButton["size"];
        "position"?: DjFloatingActionButton["position"];
      };
      "dj-form": DjVNodeBase & {
        "column"?: DjForm["column"];
      };
      "dj-global-event": DjVNodeBase & {
        "windowListeners"?: DjGlobalEvent["windowListeners"];
        "documentListeners"?: DjGlobalEvent["documentListeners"];
      };
      "dj-grid": DjVNodeBase & {
        "columns"?: DjGrid["columns"];
        "rows"?: DjGrid["rows"];
      };
      "dj-header": DjVNodeBase & {
        "sticky"?: DjHeader["sticky"];
      };
      "dj-header-card": DjVNodeBase & {
        "title"?: DjHeaderCard["title"];
        "subtitle"?: DjHeaderCard["subtitle"];
        "kind"?: DjHeaderCard["kind"];
      };
      "dj-helper-text": DjVNodeBase & {
        "text"?: DjHelperText["text"];
        "valid"?: DjHelperText["valid"];
      };
      "dj-icon": DjVNodeBase & {
        "type"?: DjIcon["type"];
        "size"?: DjIcon["size"];
        "alt-text"?: DjIcon["altText"];
      };
      "dj-label": DjVNodeBase & {
        "disabled"?: DjLabel["disabled"];
        "focused"?: DjLabel["focused"];
        "required"?: DjLabel["required"];
        "readonly"?: DjLabel["readonly"];
        "secondary"?: DjLabel["secondary"];
        "active"?: DjLabel["active"];
        "visually-hidden"?: DjLabel["visuallyHidden"];
        "valid"?: DjLabel["valid"];
        "for-id"?: DjLabel["forId"];
      };
      "dj-list": DjVNodeBase & {
        "options"?: DjList["options"];
        "value"?: DjList["value"];
        "name"?: DjList["name"];
        "label"?: DjList["label"];
        "menu"?: DjList["menu"];
        "loading"?: DjList["loading"];
        "reorderable"?: DjList["reorderable"];
      };
      "dj-loading-indicator": DjVNodeBase & {
        "active"?: DjLoadingIndicator["active"];
        "type"?: DjLoadingIndicator["type"];
      };
      "dj-native-select": DjVNodeBase & {
        "value"?: DjNativeSelect["value"];
        "name"?: DjNativeSelect["name"];
        "options"?: DjNativeSelect["options"];
        "label"?: DjNativeSelect["label"];
        "helper-text"?: DjNativeSelect["helperText"];
        "disabled"?: DjNativeSelect["disabled"];
        "required"?: DjNativeSelect["required"];
        "label-hidden"?: DjNativeSelect["labelHidden"];
        "placeholder"?: DjNativeSelect["placeholder"];
        "size"?: DjNativeSelect["size"];
      };
      "dj-number-input": DjVNodeBase & {
        "type"?: DjNumberInput["type"];
      };
      "dj-pagination": DjVNodeBase & {
        "total"?: DjPagination["total"];
        "page"?: DjPagination["page"];
        "sibling-count"?: DjPagination["siblingCount"];
      };
      "dj-password-input": DjVNodeBase & {
        "type"?: DjPasswordInput["type"];
      };
      "dj-popup": DjVNodeBase & {
        "open"?: DjPopup["open"];
        "position"?: DjPopup["position"];
        "underlay-visible"?: DjPopup["underlayVisible"];
        "scroll-lock"?: DjPopup["scrollLock"];
        "y-top"?: DjPopup["yTop"];
        "y-bottom"?: DjPopup["yBottom"];
        "x-left"?: DjPopup["xLeft"];
        "x-right"?: DjPopup["xRight"];
      };
      "dj-popup-confirmation": DjVNodeBase & {
        "open"?: DjPopupConfirmation["open"];
        "confirm-label"?: DjPopupConfirmation["confirmLabel"];
        "cancel-label"?: DjPopupConfirmation["cancelLabel"];
      };
      "dj-progress": DjVNodeBase & {
        "min"?: DjProgress["min"];
        "max"?: DjProgress["max"];
        "value"?: DjProgress["value"];
        "show-output"?: DjProgress["showOutput"];
      };
      "dj-radio": DjVNodeBase & {
        "checked"?: DjRadio["checked"];
        "value"?: DjRadio["value"];
        "name"?: DjRadio["name"];
        "disabled"?: DjRadio["disabled"];
        "required"?: DjRadio["required"];
        "label-hidden"?: DjRadio["labelHidden"];
        "tabbable"?: DjRadio["tabbable"];
      };
      "dj-radio-group": DjVNodeBase & {
        "name"?: DjRadioGroup["name"];
        "value"?: DjRadioGroup["value"];
        "options"?: DjRadioGroup["options"];
        "label"?: DjRadioGroup["label"];
        "orientation"?: DjRadioGroup["orientation"];
        "disabled"?: DjRadioGroup["disabled"];
        "required"?: DjRadioGroup["required"];
      };
      "dj-range-slider": DjVNodeBase & {
        "min"?: DjRangeSlider["min"];
        "max"?: DjRangeSlider["max"];
        "step"?: DjRangeSlider["step"];
        "value-min"?: DjRangeSlider["valueMin"];
        "value-max"?: DjRangeSlider["valueMax"];
        "name"?: DjRangeSlider["name"];
        "label"?: DjRangeSlider["label"];
        "show-output"?: DjRangeSlider["showOutput"];
        "disabled"?: DjRangeSlider["disabled"];
        "label-hidden"?: DjRangeSlider["labelHidden"];
      };
      "dj-rate": DjVNodeBase & {
        "max"?: DjRate["max"];
        "value"?: DjRate["value"];
        "allow-half"?: DjRate["allowHalf"];
        "readonly"?: DjRate["readonly"];
        "name"?: DjRate["name"];
      };
      "dj-result": DjVNodeBase & {
        "title"?: DjResult["title"];
        "subtitle"?: DjResult["subtitle"];
        "status"?: DjResult["status"];
      };
      "dj-rich-text": DjVNodeBase & {
        "value"?: DjRichText["value"];
        "name"?: DjRichText["name"];
        "label"?: DjRichText["label"];
        "placeholder"?: DjRichText["placeholder"];
        "disabled"?: DjRichText["disabled"];
        "plugins"?: DjRichText["plugins"];
        "format"?: DjRichText["format"];
        "sanitizePaste"?: DjRichText["sanitizePaste"];
        "pasteSanitizer"?: DjRichText["pasteSanitizer"];
      };
      "dj-select": DjVNodeBase & {
        "options"?: DjSelect["options"];
        "value"?: DjSelect["value"];
        "name"?: DjSelect["name"];
        "label"?: DjSelect["label"];
        "helper-text"?: DjSelect["helperText"];
        "placeholder"?: DjSelect["placeholder"];
        "disabled"?: DjSelect["disabled"];
        "required"?: DjSelect["required"];
        "position"?: DjSelect["position"];
        "open"?: DjSelect["open"];
      };
      "dj-slide-pane": DjVNodeBase & {
        "open"?: DjSlidePane["open"];
        "align"?: DjSlidePane["align"];
        "width"?: DjSlidePane["width"];
        "underlay"?: DjSlidePane["underlay"];
        "close-text"?: DjSlidePane["closeText"];
      };
      "dj-slider": DjVNodeBase & {
        "min"?: DjSlider["min"];
        "max"?: DjSlider["max"];
        "step"?: DjSlider["step"];
        "value"?: DjSlider["value"];
        "name"?: DjSlider["name"];
        "label"?: DjSlider["label"];
        "show-output"?: DjSlider["showOutput"];
        "disabled"?: DjSlider["disabled"];
        "readonly"?: DjSlider["readonly"];
        "required"?: DjSlider["required"];
        "label-hidden"?: DjSlider["labelHidden"];
      };
      "dj-snackbar": DjVNodeBase & {
        "open"?: DjSnackbar["open"];
        "type"?: DjSnackbar["type"];
        "leading"?: DjSnackbar["leading"];
        "stacked"?: DjSnackbar["stacked"];
      };
      "dj-speed-dial": DjVNodeBase & {
        "open"?: DjSpeedDial["open"];
        "direction"?: DjSpeedDial["direction"];
      };
      "dj-split-panel": DjVNodeBase & {
        "orientation"?: DjSplitPanel["orientation"];
        "position"?: DjSplitPanel["position"];
        "disabled"?: DjSplitPanel["disabled"];
      };
      "dj-stack": DjVNodeBase & {
        "direction"?: DjStack["direction"];
        "align"?: DjStack["align"];
        "spacing"?: DjStack["spacing"];
        "padding"?: DjStack["padding"];
        "stretch"?: DjStack["stretch"];
      };
      "dj-switch": DjVNodeBase & {
        "checked"?: DjSwitch["checked"];
        "value"?: DjSwitch["value"];
        "name"?: DjSwitch["name"];
        "disabled"?: DjSwitch["disabled"];
        "readonly"?: DjSwitch["readonly"];
        "label-hidden"?: DjSwitch["labelHidden"];
      };
      "dj-tab-container": DjVNodeBase & {
        "tabs"?: DjTabContainer["tabs"];
        "active-index"?: DjTabContainer["activeIndex"];
        "align-buttons"?: DjTabContainer["alignButtons"];
      };
      "dj-text": DjVNodeBase & {
        "size"?: DjText["size"];
        "weight"?: DjText["weight"];
        "inverse"?: DjText["inverse"];
        "truncated"?: DjText["truncated"];
        "uppercase"?: DjText["uppercase"];
      };
      "dj-text-area": DjVNodeBase & {
        "value"?: DjTextArea["value"];
        "name"?: DjTextArea["name"];
        "placeholder"?: DjTextArea["placeholder"];
        "label"?: DjTextArea["label"];
        "helper-text"?: DjTextArea["helperText"];
        "rows"?: DjTextArea["rows"];
        "cols"?: DjTextArea["cols"];
        "wrap"?: DjTextArea["wrap"];
        "disabled"?: DjTextArea["disabled"];
        "readonly"?: DjTextArea["readonly"];
        "required"?: DjTextArea["required"];
        "label-hidden"?: DjTextArea["labelHidden"];
        "minlength"?: DjTextArea["minlength"];
        "maxlength"?: DjTextArea["maxlength"];
      };
      "dj-text-input": DjVNodeBase & {
        "value"?: DjTextInput["value"];
        "type"?: DjTextInput["type"];
        "name"?: DjTextInput["name"];
        "placeholder"?: DjTextInput["placeholder"];
        "label"?: DjTextInput["label"];
        "helper-text"?: DjTextInput["helperText"];
        "disabled"?: DjTextInput["disabled"];
        "readonly"?: DjTextInput["readonly"];
        "required"?: DjTextInput["required"];
        "label-hidden"?: DjTextInput["labelHidden"];
        "autocomplete"?: DjTextInput["autocomplete"];
        "pattern"?: DjTextInput["pattern"];
        "min"?: DjTextInput["min"];
        "max"?: DjTextInput["max"];
        "step"?: DjTextInput["step"];
        "minlength"?: DjTextInput["minlength"];
        "maxlength"?: DjTextInput["maxlength"];
      };
      "dj-theme": DjVNodeBase & {
        "theme"?: DjTheme["theme"];
      };
      "dj-three-column-layout": DjVNodeBase;
      "dj-time-picker": DjVNodeBase & {
        "value"?: DjTimePicker["value"];
        "name"?: DjTimePicker["name"];
        "label"?: DjTimePicker["label"];
        "min"?: DjTimePicker["min"];
        "max"?: DjTimePicker["max"];
        "step"?: DjTimePicker["step"];
        "format"?: DjTimePicker["format"];
        "disabled"?: DjTimePicker["disabled"];
        "required"?: DjTimePicker["required"];
      };
      "dj-title-pane": DjVNodeBase & {
        "name"?: DjTitlePane["name"];
        "open"?: DjTitlePane["open"];
        "closeable"?: DjTitlePane["closeable"];
        "heading-level"?: DjTitlePane["headingLevel"];
      };
      "dj-toolbar": DjVNodeBase & {
        "label"?: DjToolbar["label"];
        "sticky"?: DjToolbar["sticky"];
        "overflow"?: DjToolbar["overflow"];
        "overflow-position"?: DjToolbar["overflowPosition"];
      };
      "dj-tooltip": DjVNodeBase & {
        "open"?: DjTooltip["open"];
        "orientation"?: DjTooltip["orientation"];
      };
      "dj-transition": DjVNodeBase & {
        "show"?: DjTransition["show"];
        "appear"?: DjTransition["appear"];
        "state"?: DjTransition["state"];
      };
      "dj-transition-group": DjVNodeBase & {
        "show"?: DjTransitionGroup["show"];
        "stagger"?: DjTransitionGroup["stagger"];
      };
      "dj-tree": DjVNodeBase & {
        "nodes"?: DjTree["nodes"];
        "value"?: DjTree["value"];
        "expanded"?: DjTree["expanded"];
      };
      "dj-trigger-popup": DjVNodeBase & {
        "open"?: DjTriggerPopup["open"];
        "position"?: DjTriggerPopup["position"];
        "match-width"?: DjTriggerPopup["matchWidth"];
        "underlay-visible"?: DjTriggerPopup["underlayVisible"];
      };
      "dj-two-column-layout": DjVNodeBase & {
        "bias"?: DjTwoColumnLayout["bias"];
      };
      "dj-typeahead": DjVNodeBase & {
        "options"?: DjTypeahead["options"];
        "value"?: DjTypeahead["value"];
        "name"?: DjTypeahead["name"];
        "label"?: DjTypeahead["label"];
        "placeholder"?: DjTypeahead["placeholder"];
        "helper-text"?: DjTypeahead["helperText"];
        "disabled"?: DjTypeahead["disabled"];
        "required"?: DjTypeahead["required"];
        "strict"?: DjTypeahead["strict"];
        "position"?: DjTypeahead["position"];
      };
      "dj-video": DjVNodeBase & {
        "sources"?: DjVideo["sources"];
        "src"?: DjVideo["src"];
        "poster"?: DjVideo["poster"];
        "muted"?: DjVideo["muted"];
        "autoplay"?: DjVideo["autoplay"];
        "loop"?: DjVideo["loop"];
        "tracks"?: DjVideo["tracks"];
        "label"?: DjVideo["label"];
      };
      "dj-wizard": DjVNodeBase & {
        "steps"?: DjWizard["steps"];
        "active-step"?: DjWizard["activeStep"];
        "direction"?: DjWizard["direction"];
        "clickable"?: DjWizard["clickable"];
      };
    }
  }
}

// Dojo VNode properties common to every element (mirrors VNodeProperties:
// key/classes/styles plus on* event handlers). Named dj- props above add precise
// types on top; an unknown `kind` value still errors because the explicit member
// is narrower than this base.
interface DjVNodeBase {
  key?: string | number;
  classes?: string | null | undefined | (string | null | undefined | boolean)[];
  styles?: Partial<CSSStyleDeclaration>;
  [handler: `on${string}`]: ((event: any) => void) | undefined;
}
