/**
 * Curated emoji set for `@dojo-ng/rich-text-emoji`. ~170 entries across exactly 8 categories. Each
 * `ch` is a single grapheme (no skin-tone or ZWJ-sequence variants), each `shortcode` is a unique
 * GitHub-style `[a-z0-9_+-]+`, and every entry has a non-empty English `name`. These invariants are
 * test-enforced (see `tests/rich-text-emoji.test.js`).
 */
export interface EmojiEntry {
	ch: string;
	name: string;
	shortcode: string;
	keywords?: string[];
	category: string;
}

export const EMOJI: EmojiEntry[] = [
	// --- smileys ---
	{ ch: "😀", name: "grinning face", shortcode: "grinning", keywords: ["smile", "happy"], category: "smileys" },
	{ ch: "😃", name: "smiling face with open mouth", shortcode: "smiley", category: "smileys" },
	{ ch: "😄", name: "grinning face with smiling eyes", shortcode: "smile", category: "smileys" },
	{ ch: "😁", name: "beaming face with smiling eyes", shortcode: "grin", category: "smileys" },
	{ ch: "😆", name: "grinning squinting face", shortcode: "laughing", keywords: ["lol"], category: "smileys" },
	{ ch: "😅", name: "grinning face with sweat", shortcode: "sweat_smile", category: "smileys" },
	{ ch: "🤣", name: "rolling on the floor laughing", shortcode: "rofl", keywords: ["lol"], category: "smileys" },
	{ ch: "😂", name: "face with tears of joy", shortcode: "joy", keywords: ["lol", "cry"], category: "smileys" },
	{ ch: "🙂", name: "slightly smiling face", shortcode: "slightly_smiling_face", category: "smileys" },
	{ ch: "🙃", name: "upside-down face", shortcode: "upside_down_face", category: "smileys" },
	{ ch: "😉", name: "winking face", shortcode: "wink", category: "smileys" },
	{ ch: "😊", name: "smiling face with smiling eyes", shortcode: "blush", category: "smileys" },
	{ ch: "😇", name: "smiling face with halo", shortcode: "innocent", category: "smileys" },
	{ ch: "😍", name: "smiling face with heart-eyes", shortcode: "heart_eyes", keywords: ["love"], category: "smileys" },
	{ ch: "😘", name: "face blowing a kiss", shortcode: "kissing_heart", category: "smileys" },
	{ ch: "😋", name: "face savoring food", shortcode: "yum", category: "smileys" },
	{ ch: "😜", name: "winking face with tongue", shortcode: "stuck_out_tongue_winking_eye", category: "smileys" },
	{ ch: "🤪", name: "zany face", shortcode: "zany_face", category: "smileys" },
	{ ch: "🤗", name: "hugging face", shortcode: "hugs", category: "smileys" },
	{ ch: "🤔", name: "thinking face", shortcode: "thinking", category: "smileys" },
	{ ch: "😐", name: "neutral face", shortcode: "neutral_face", category: "smileys" },
	{ ch: "😴", name: "sleeping face", shortcode: "sleeping", category: "smileys" },
	{ ch: "😎", name: "smiling face with sunglasses", shortcode: "sunglasses", keywords: ["cool"], category: "smileys" },
	{ ch: "🤩", name: "star-struck", shortcode: "star_struck", category: "smileys" },

	// --- people ---
	{ ch: "👍", name: "thumbs up", shortcode: "thumbsup", keywords: ["+1", "yes"], category: "people" },
	{ ch: "👎", name: "thumbs down", shortcode: "thumbsdown", keywords: ["-1", "no"], category: "people" },
	{ ch: "👌", name: "OK hand", shortcode: "ok_hand", category: "people" },
	{ ch: "👋", name: "waving hand", shortcode: "wave", category: "people" },
	{ ch: "🤚", name: "raised back of hand", shortcode: "raised_back_of_hand", category: "people" },
	{ ch: "✋", name: "raised hand", shortcode: "raised_hand", category: "people" },
	{ ch: "🖖", name: "vulcan salute", shortcode: "vulcan", category: "people" },
	{ ch: "👏", name: "clapping hands", shortcode: "clap", category: "people" },
	{ ch: "🙌", name: "raising hands", shortcode: "raised_hands", category: "people" },
	{ ch: "🙏", name: "folded hands", shortcode: "pray", keywords: ["thanks"], category: "people" },
	{ ch: "🤝", name: "handshake", shortcode: "handshake", category: "people" },
	{ ch: "💪", name: "flexed biceps", shortcode: "muscle", category: "people" },
	{ ch: "👀", name: "eyes", shortcode: "eyes", category: "people" },
	{ ch: "👶", name: "baby", shortcode: "baby", category: "people" },
	{ ch: "🧑", name: "person", shortcode: "person", category: "people" },
	{ ch: "👦", name: "boy", shortcode: "boy", category: "people" },
	{ ch: "👧", name: "girl", shortcode: "girl", category: "people" },
	{ ch: "👨", name: "man", shortcode: "man", category: "people" },
	{ ch: "👩", name: "woman", shortcode: "woman", category: "people" },
	{ ch: "🧓", name: "older person", shortcode: "older_person", category: "people" },
	{ ch: "💃", name: "woman dancing", shortcode: "dancer", category: "people" },
	{ ch: "🚶", name: "person walking", shortcode: "walking", category: "people" },

	// --- hearts ---
	{ ch: "❤️", name: "red heart", shortcode: "heart", keywords: ["love"], category: "hearts" },
	{ ch: "🧡", name: "orange heart", shortcode: "orange_heart", category: "hearts" },
	{ ch: "💛", name: "yellow heart", shortcode: "yellow_heart", category: "hearts" },
	{ ch: "💚", name: "green heart", shortcode: "green_heart", category: "hearts" },
	{ ch: "💙", name: "blue heart", shortcode: "blue_heart", category: "hearts" },
	{ ch: "💜", name: "purple heart", shortcode: "purple_heart", category: "hearts" },
	{ ch: "🖤", name: "black heart", shortcode: "black_heart", category: "hearts" },
	{ ch: "🤍", name: "white heart", shortcode: "white_heart", category: "hearts" },
	{ ch: "🤎", name: "brown heart", shortcode: "brown_heart", category: "hearts" },
	{ ch: "💔", name: "broken heart", shortcode: "broken_heart", category: "hearts" },
	{ ch: "❣️", name: "heart exclamation", shortcode: "heavy_heart_exclamation", category: "hearts" },
	{ ch: "💕", name: "two hearts", shortcode: "two_hearts", category: "hearts" },
	{ ch: "💞", name: "revolving hearts", shortcode: "revolving_hearts", category: "hearts" },
	{ ch: "💓", name: "beating heart", shortcode: "heartbeat", category: "hearts" },
	{ ch: "💗", name: "growing heart", shortcode: "heartpulse", category: "hearts" },
	{ ch: "💖", name: "sparkling heart", shortcode: "sparkling_heart", category: "hearts" },
	{ ch: "💘", name: "heart with arrow", shortcode: "cupid", category: "hearts" },
	{ ch: "💝", name: "heart with ribbon", shortcode: "gift_heart", category: "hearts" },
	{ ch: "💟", name: "heart decoration", shortcode: "heart_decoration", category: "hearts" },
	{ ch: "♥️", name: "heart suit", shortcode: "hearts", category: "hearts" },

	// --- animals ---
	{ ch: "🐶", name: "dog face", shortcode: "dog", category: "animals" },
	{ ch: "🐱", name: "cat face", shortcode: "cat", category: "animals" },
	{ ch: "🐭", name: "mouse face", shortcode: "mouse", category: "animals" },
	{ ch: "🐹", name: "hamster", shortcode: "hamster", category: "animals" },
	{ ch: "🐰", name: "rabbit face", shortcode: "rabbit", category: "animals" },
	{ ch: "🦊", name: "fox", shortcode: "fox", category: "animals" },
	{ ch: "🐻", name: "bear", shortcode: "bear", category: "animals" },
	{ ch: "🐼", name: "panda", shortcode: "panda", category: "animals" },
	{ ch: "🐨", name: "koala", shortcode: "koala", category: "animals" },
	{ ch: "🐯", name: "tiger face", shortcode: "tiger", category: "animals" },
	{ ch: "🦁", name: "lion", shortcode: "lion", category: "animals" },
	{ ch: "🐮", name: "cow face", shortcode: "cow", category: "animals" },
	{ ch: "🐷", name: "pig face", shortcode: "pig", category: "animals" },
	{ ch: "🐸", name: "frog", shortcode: "frog", category: "animals" },
	{ ch: "🐵", name: "monkey face", shortcode: "monkey", category: "animals" },
	{ ch: "🐔", name: "chicken", shortcode: "chicken", category: "animals" },
	{ ch: "🐧", name: "penguin", shortcode: "penguin", category: "animals" },
	{ ch: "🐦", name: "bird", shortcode: "bird", category: "animals" },
	{ ch: "🦆", name: "duck", shortcode: "duck", category: "animals" },
	{ ch: "🦉", name: "owl", shortcode: "owl", category: "animals" },
	{ ch: "🐺", name: "wolf", shortcode: "wolf", category: "animals" },
	{ ch: "🐴", name: "horse face", shortcode: "horse", category: "animals" },

	// --- food ---
	{ ch: "🍏", name: "green apple", shortcode: "green_apple", category: "food" },
	{ ch: "🍎", name: "red apple", shortcode: "apple", category: "food" },
	{ ch: "🍐", name: "pear", shortcode: "pear", category: "food" },
	{ ch: "🍊", name: "tangerine", shortcode: "tangerine", keywords: ["orange"], category: "food" },
	{ ch: "🍋", name: "lemon", shortcode: "lemon", category: "food" },
	{ ch: "🍌", name: "banana", shortcode: "banana", category: "food" },
	{ ch: "🍉", name: "watermelon", shortcode: "watermelon", category: "food" },
	{ ch: "🍇", name: "grapes", shortcode: "grapes", category: "food" },
	{ ch: "🍓", name: "strawberry", shortcode: "strawberry", category: "food" },
	{ ch: "🍒", name: "cherries", shortcode: "cherries", category: "food" },
	{ ch: "🍑", name: "peach", shortcode: "peach", category: "food" },
	{ ch: "🍍", name: "pineapple", shortcode: "pineapple", category: "food" },
	{ ch: "🥝", name: "kiwi fruit", shortcode: "kiwi", category: "food" },
	{ ch: "🍅", name: "tomato", shortcode: "tomato", category: "food" },
	{ ch: "🥑", name: "avocado", shortcode: "avocado", category: "food" },
	{ ch: "🍆", name: "eggplant", shortcode: "eggplant", category: "food" },
	{ ch: "🥕", name: "carrot", shortcode: "carrot", category: "food" },
	{ ch: "🌽", name: "ear of corn", shortcode: "corn", category: "food" },
	{ ch: "🍔", name: "hamburger", shortcode: "hamburger", keywords: ["burger"], category: "food" },
	{ ch: "🍟", name: "french fries", shortcode: "fries", category: "food" },
	{ ch: "🍕", name: "pizza", shortcode: "pizza", category: "food" },
	{ ch: "🌮", name: "taco", shortcode: "taco", category: "food" },

	// --- activities ---
	{ ch: "⚽", name: "soccer ball", shortcode: "soccer", category: "activities" },
	{ ch: "🏀", name: "basketball", shortcode: "basketball", category: "activities" },
	{ ch: "🏈", name: "american football", shortcode: "football", category: "activities" },
	{ ch: "⚾", name: "baseball", shortcode: "baseball", category: "activities" },
	{ ch: "🎾", name: "tennis", shortcode: "tennis", category: "activities" },
	{ ch: "🏐", name: "volleyball", shortcode: "volleyball", category: "activities" },
	{ ch: "🏉", name: "rugby football", shortcode: "rugby_football", category: "activities" },
	{ ch: "🎱", name: "pool 8 ball", shortcode: "8ball", keywords: ["billiards"], category: "activities" },
	{ ch: "🏓", name: "ping pong", shortcode: "ping_pong", category: "activities" },
	{ ch: "🏸", name: "badminton", shortcode: "badminton", category: "activities" },
	{ ch: "🥅", name: "goal net", shortcode: "goal_net", category: "activities" },
	{ ch: "🏒", name: "ice hockey", shortcode: "hockey", category: "activities" },
	{ ch: "🏑", name: "field hockey", shortcode: "field_hockey", category: "activities" },
	{ ch: "🏏", name: "cricket game", shortcode: "cricket", category: "activities" },
	{ ch: "⛳", name: "flag in hole", shortcode: "golf", category: "activities" },
	{ ch: "🏹", name: "bow and arrow", shortcode: "bow_and_arrow", category: "activities" },
	{ ch: "🎣", name: "fishing pole", shortcode: "fishing_pole", category: "activities" },
	{ ch: "🥊", name: "boxing glove", shortcode: "boxing_glove", category: "activities" },
	{ ch: "🎿", name: "skis", shortcode: "ski", category: "activities" },
	{ ch: "🛹", name: "skateboard", shortcode: "skateboard", category: "activities" },

	// --- objects ---
	{ ch: "⌚", name: "watch", shortcode: "watch", category: "objects" },
	{ ch: "📱", name: "mobile phone", shortcode: "iphone", keywords: ["phone"], category: "objects" },
	{ ch: "💻", name: "laptop", shortcode: "computer", category: "objects" },
	{ ch: "⌨️", name: "keyboard", shortcode: "keyboard", category: "objects" },
	{ ch: "🖥️", name: "desktop computer", shortcode: "desktop", category: "objects" },
	{ ch: "🖨️", name: "printer", shortcode: "printer", category: "objects" },
	{ ch: "🖱️", name: "computer mouse", shortcode: "mouse_three_button", category: "objects" },
	{ ch: "💾", name: "floppy disk", shortcode: "floppy_disk", keywords: ["save"], category: "objects" },
	{ ch: "💿", name: "optical disk", shortcode: "cd", category: "objects" },
	{ ch: "📀", name: "dvd", shortcode: "dvd", category: "objects" },
	{ ch: "📷", name: "camera", shortcode: "camera", category: "objects" },
	{ ch: "📸", name: "camera with flash", shortcode: "camera_flash", category: "objects" },
	{ ch: "🎥", name: "movie camera", shortcode: "movie_camera", category: "objects" },
	{ ch: "📞", name: "telephone receiver", shortcode: "telephone_receiver", category: "objects" },
	{ ch: "📟", name: "pager", shortcode: "pager", category: "objects" },
	{ ch: "📺", name: "television", shortcode: "tv", category: "objects" },
	{ ch: "📻", name: "radio", shortcode: "radio", category: "objects" },
	{ ch: "🔋", name: "battery", shortcode: "battery", category: "objects" },
	{ ch: "🔌", name: "electric plug", shortcode: "electric_plug", category: "objects" },
	{ ch: "💡", name: "light bulb", shortcode: "bulb", keywords: ["idea"], category: "objects" },
	{ ch: "🔦", name: "flashlight", shortcode: "flashlight", category: "objects" },
	{ ch: "📖", name: "open book", shortcode: "book", category: "objects" },

	// --- symbols ---
	{ ch: "✅", name: "check mark button", shortcode: "white_check_mark", keywords: ["done"], category: "symbols" },
	{ ch: "❌", name: "cross mark", shortcode: "x", category: "symbols" },
	{ ch: "⭕", name: "hollow red circle", shortcode: "o", category: "symbols" },
	{ ch: "❓", name: "question mark", shortcode: "question", category: "symbols" },
	{ ch: "❗", name: "exclamation mark", shortcode: "exclamation", category: "symbols" },
	{ ch: "💯", name: "hundred points", shortcode: "100", category: "symbols" },
	{ ch: "🔥", name: "fire", shortcode: "fire", category: "symbols" },
	{ ch: "⭐", name: "star", shortcode: "star", category: "symbols" },
	{ ch: "🌟", name: "glowing star", shortcode: "star2", category: "symbols" },
	{ ch: "✨", name: "sparkles", shortcode: "sparkles", category: "symbols" },
	{ ch: "⚡", name: "high voltage", shortcode: "zap", category: "symbols" },
	{ ch: "❄️", name: "snowflake", shortcode: "snowflake", category: "symbols" },
	{ ch: "💧", name: "droplet", shortcode: "droplet", category: "symbols" },
	{ ch: "☀️", name: "sun", shortcode: "sunny", category: "symbols" },
	{ ch: "🌈", name: "rainbow", shortcode: "rainbow", category: "symbols" },
	{ ch: "🎉", name: "party popper", shortcode: "tada", keywords: ["celebrate"], category: "symbols" },
	{ ch: "🎊", name: "confetti ball", shortcode: "confetti_ball", category: "symbols" },
	{ ch: "🔔", name: "bell", shortcode: "bell", category: "symbols" },
	{ ch: "🔒", name: "locked", shortcode: "lock", category: "symbols" },
	{ ch: "🔑", name: "key", shortcode: "key", category: "symbols" },
];
